version: "3"
services:
  nginx:
    image: nginx:1.15.7-alpine
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./log:/var/log/nginx
    environment:
      TZ: Asia/Shanghai
    ports:
    - 80:80
  filebeat:
    image: elastic/filebeat:7.5.1
    volumes:
    - ./log:/var/log/nginx
    - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
    - nginx
  zookeeper:
    image: zookeeper:3.5.6
    ports:
    - 2181:2181
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    ports:
    - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://127.0.0.1:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://127.0.0.1:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
    - zookeeper
  elasticsearch:
    image: elasticsearch:7.5.1
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx128m -Xms128m"
  logstash:
    image: logstash:7.5.1
    volumes:
    - ./nginx-log-pipeline.conf:/usr/share/logstash/pipeline/nginx-log-pipeline.conf
    # - ./nginx-log-template.json:/usr/share/logstash/pipeline/nginx-log-template.json
    # entrypoint:
    # - logstash
    # - -f
    # - /usr/share/logstash/config/logstash.yml
    environment:
      LS_JAVA_OPTS: "-Xmx128m -Xms128m"
    depends_on:
    - kafka
    - elasticsearch
  kibana:
    image: kibana:7.5.1
    ports:
    - 5601:5601
    # environment:
    #   ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
    - elasticsearch
